// Automatically generated by astro-icon
// 98d29eb32eeed1ef0270aa9f754d77714124da2314bdd93204ff1ff15ec1110f

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "chevron-down"
		| "close"
		| "collapse"
		| "download"
		| "error"
		| "expand"
		| "graphql"
		| "hamburger-menu"
		| "help"
		| "openapi"
		| "required"
		| "success"
		| "sync"
		| "unknown"
		| "update"
		| "warning";
}