// Automatically generated by astro-icon
// 6e4c0fafff72f15503d2a0d971ee00de5850c18eca8cb601555f932f96d50654

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "chevron-down"
		| "close"
		| "collapse"
		| "download"
		| "error"
		| "expand"
		| "graphql"
		| "hamburger-menu"
		| "openapi"
		| "required"
		| "success"
		| "sync"
		| "unknown"
		| "update"
		| "warning";
}