outputFolder: /docs
base: /chess
title: Chess Game API Example
logo:
  url: /data/logo.svg
  width: 100
  height: 100
apis:
  - id: graphql
    name: Chess Game GraphQL API
    url: /data/schemas/chess-game-schema.graphql

  - id: openapi
    name: Chess Game OpenAPI 3.0
    url: /data/schemas/chess-game-30.json
customPagesFolder: /data/custom-pages

examplesFolder: /data/usage-examples
groups:
  - name: Player
    regex: /player|move/i
  - name: Game
    regex: /game/i
  - name: Admin
    regex: /admin/i
