name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'



      - name: Install dependencies
        run: pnpm install

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: pnpm commitlint --last --verbose

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: pnpm commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose




      - name: Code Check - format, lint
        run: pnpm check

      - name: Build CLI
        run: pnpm build-cli

      - name: E2E Tests
        run: pnpm vitest --coverage.enabled true

      - name: Report Coverage
        if: always()
        uses:  davelosert/vitest-coverage-report-action@v2

      - name: Trigger public site deployment
        if: github.event_name == 'push'
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.FXDX_GITHUB_TOKEN }}" \
            https://api.github.com/repos/flexydox/flexydox.github.io/actions/workflows/100774633/dispatches \
            -d '{"ref":"main"}'
