name: Generate and deploy API documentation

on:
  workflow_dispatch:
jobs:
  update_homepage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: S3 Deploy - Homepage
        run: aws s3 cp ./examples/sites/index.html s3://fxdx/index.html
  deploy_app:
    strategy:
      matrix:
        api:
        - chess
        - github
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Run generators
        run: cd examples && docker-compose -f "./docker-compose.yml" up ${{ matrix.api }}

      - name: S3 Deploy - ${{ matrix.api }}
        run: aws s3 sync ./examples/docs/${{ matrix.api }}/site s3://fxdx/${{ matrix.api }} --delete
